name = "NyaMON"
author = "AlexBJU"
version = "1.67.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "482a8e3a34eb29e391f2b11bfd8ef75f2a29e4644a697491126d0425790f9fff"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
