name = "NyaMON"
author = "AlexBJU"
version = "1.67.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9afc040cb2d987ee8e9273e9e9d283df2a68b1652afa5c4ada35383c434b2c76"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
