name = "NyaMON"
author = "AlexBJU"
version = "1.67.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2d08d7d6055b873260c6a4532675de750af56ac2f057efc2bc3af82a5779fc3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
